mainClass="com.kuleuven.test_reducer.TestReducer"
clustersPath="thesis_code/data/commons_math/clusters/girvan_newman/clusters.json"
testInput="systems/commons-math/src/test"
testOutput="systems/commons-math/src/reduced_test_girvan_newman"
jarPath="target/libs/commons-math3-3.6.1.jar"
srcDir="systems/commons-math/src"
mvn exec:java -Dexec.mainClass=$mainClass -Dexec.args="$clustersPath $testInput $testOutput $jarPath $srcDir"
